# Generated by Django 6.0.4 on 2026-05-06.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('keyword', models.CharField(max_length=80)),
                ('article_title', models.CharField(max_length=240)),
                ('article_url', models.URLField()),
                ('source', models.CharField(max_length=120)),
                (
                    'severity',
                    models.CharField(
                        choices=[
                            ('medium', 'Medium'),
                            ('high', 'High'),
                            ('critical', 'Critical'),
                        ],
                        default='medium',
                        max_length=20,
                    ),
                ),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='newsalert',
            constraint=models.UniqueConstraint(
                fields=('keyword', 'article_url'),
                name='unique_keyword_per_article',
            ),
        ),
    ]
