# Generated by Django 6.0.4 on 2026-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_newsalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsalert',
            name='institution_keyword',
            field=models.CharField(db_index=True, default='general', max_length=80),
        ),
    ]
