# Generated by Django 6.0.4 on 2026-05-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0003_newsalert_institution_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsalert',
            name='institution_keyword',
        ),
    ]
